### ISSUE TITLE
STORY B12: As a third party developer I want the metadata to contain a link to a mediafile if the mediafile is available under an open license

### ISSUE THREAD

**Issue by 85jesse** [beeldengeluid/opendatalab#18]
EPIC B12: As a third party developer I want the metadata to contain a link to a mediafile if the mediafile is available under an open license so I can make the mediafile accessible via my own platform.

**Acceptance criteria**
[ ] Initially this link can be from Open Beelden, Soundcloud and in.beeldengeluid.nl
[ ] In the future, when other solutions for mediastream/mediadownload come available (e.g. Peertube, GPP) we want to be able to change these links in the data to new ones.

**Comment by 85jesse** [comment]
We will have to figure out how to match the OpenBeelden and Soundcloud stuff with the DAAN metadata. Since Taak-ids are no longer used in DAAN I'm not sure which fields are best for matching.

**Comment by wmelder** [comment]
This is realized for the OpenBeelden items, because we have links to these items in our catalogue open data. Also, the link to the item on the OpenBeelden platform is added. in.beeldengeluid.nl is kind of dead, so maybe we might have to do it for SoundCloud one day... or Wikimedia Commons...
For now, I think we provided a solution and if we need to engineer something more specific, we will create a specific issue for this.
