### ISSUE TITLE
STORY B4 As an innovation manager I want all GTAA-concepts within the metadata to contain a persistent GTAA-URI

### ISSUE THREAD

**Issue by 85jesse** [beeldengeluid/opendatalab#7]
STORY B4 As an innovation manager I want all GTAA-concepts within the metadata to contain a persistent GTAA-URI	so that I can built a graph in which relations between GTAA-terms and other, external information sources can be combined with the metadata.

Relation with Story B3, but for another (future) application: the linking between our metadata and external sources within a knowledge graph.

**Comment by wmelder** [comment]
in fact this requirement is already met by the latest beng-lod server. It maps the available thesaurus ID's to the right SKOS concepts.
One remark: the concepts from the nongtaa and expired sets will be replaced with /gtaa URI's. That will not be a problem, since these concepts are not used frequently. The GTAA concept URI's will remain unchanged.
